# Site settings
title: Software that grows your business
email: ladislav@slowpath.com
description: > # this means to ignore newlines until "baseurl:"
  We are small team of enthusiastic programmers, designers building well crafted software that helps you grow your business.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://slowpath.com" # the base hostname & protocol for your site
twitter_username: slowpathcom
github_username: slowpath

# Build settings
markdown: kramdown
